In [3]:
import numpy as np

In [ ]:
N = int(input ('Введите N:'))

In [10]:
# Задание первое, первый вариант
result = np.arange(N-1, -1, -1)
print (result)

Введите N: 10


[9 8 7 6 5 4 3 2 1 0]


In [41]:
# Задание первое, второй вариант
result = np.linspace(N-1, 0, N)
result = result.astype(np.int32)
print (result)

[9 8 7 6 5 4 3 2 1 0]


In [43]:
# Задание второе
matrix = np.diag(np.arange(N), k=0)
response = np.zeros((N,N))
count = N-1
for line in matrix:
    response[count][count] = line[N-1-count]
    count -= 1
result = int(np.trace(response))
print (result)

45


In [ ]:
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [50]:
# Задание третье
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
с = linalg.solve(a, b)
print(с)
np.allclose( np.dot(a, с), b )

[ 0.46666667  3.84444444 -5.55555556]


True